# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Wear Audio Recorder
email: recorder.dev@gmail.com
description: Minimalistic, Material app to record your thoughts, lectures and any other important moment of your life
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mobileapplandingpage.learn.uno" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: ArtursTwit
github_username:  gaket
author: Artur Badretdinov
logo: assets/images/large-logo.png
twitter:
  username: ArtursTwit
social:
  name: Sandoche Adittane
  links:
    - https://twitter.com/arturstwit
    - https://www.linkedin.com/in/arturkuzmin
    - https://github.com/gaket

languages: ["en"]
ampdir: amp

github: https://github.com/sandoche/Mobile-app-landingpage-template

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
